config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :recipes
  resources :items
  resources :lists
  resources :users

  resources :sessions, only: [:create]
  get '/sessions', to: 'sessions#new'
  delete '/sessions', to: 'sessions#destroy', as: 'logout'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/recipes/:id', to: 'recipes#add_to_list', as: 'add_to_list'
  post '/lists/:id', to: 'lists#share', as: 'share_list'

  get '/recipe_search', to: 'recipes#search', as: 'recipe_search'
  get '/list_search', to: 'lists#search', as: 'list_search'
end

app/models/list.rb
class List < ApplicationRecord
    has_many :list_items
    has_many :items, through: :list_items
    has_many :user_lists
    has_many :users, through: :user_lists
    accepts_nested_attributes_for :items, :list_items

    validates :name, presence: true

    # Here we want to 
    def items_attributes=(item_attributes)
        item_attributes.values.each do |item_attributes|
            if item_attributes[:name] != ""
                item = Item.find_or_create_by(item_attributes)
                item.update(name: item.name.downcase)
                self.items << item
            end
        end
    end

    def list_items_attributes=(list_item_attributes)
        list_item_attributes.values.each do |list_item_attributes|
            list_item = ListItem.find_or_create_by(list_item_attributes)
            self.list_items << list_item
        end
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy, :share]

  def index
    @lists = List.all
  end

  def new
    @list = List.new

    8.times do
      @list.items.new
    end
  end

  def create
    @list  = List.new(list_params)
    if @list.save
      UserList.create(user_id: session[:user_id],list_id: @list.id)
      redirect_to @list
    else
      flash[:errors] = @list.errors.full_messages
      redirect_to new_list_path
    end
  end

  def show
  end

  def edit
    4.times do
      @list.items.new
    end
  end

  def update
    ListItem.where(list_id: @list.id).destroy_all
    @list.update(list_params)
    redirect_to @list
  end

  def destroy
    @list.list_items.each do |list_item|
      list_item.destroy
    end
    @list.user_lists.each do |user_list|
      user_list.destroy
    end
    @list.destroy
    redirect_to lists_path
  end

  def share
    if UserList.find_by(user_id: params[:user_id], list_id: @list.id)
      flash[:alert] = "Already shared list with #{User.find(params[:user_id]).name}!"
    else
      UserList.find_or_create_by(user_id: params[:user_id], list_id: @list.id)
      flash[:notice] = "Shared list with #{User.find(params[:user_id]).name}!"
    end
    redirect_to @list
  end

  def search
    # search_item = Item.find_by(name: params[:q])
    @q = params[:q].downcase
    @search_item = Item.where('name LIKE ?', "%#{@q}%")


    if @search_item == [] || @q == "" || @q == " "
      flash[:alert] = "No lists include #{@q}."
      render :index
    else
      flash.clear
      @search_item
      render :index
    end
  end
  private

  def list_params
    params.require(:list).permit(:name, item_ids:[], items_attributes: [:name])
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/edit.html.erb
<% content_for :title do %>Edit <%= @list.name.titlecase %> List<% end %>
<% content_for :description do %>My Description<% end %>

<% if flash[:errors] %>
    <ul>
    <% flash[:errors].each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

<%= form_with model: @list do |f| %>
    <h2>List name: <%= f.text_field :name %></h2>
    <h2>Items: </h2><%= f.fields_for :items do |item| %>
        <p><%= item.text_field :name %></p>
    <% end %>
    <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<% content_for :title do %>Lists<% end %>
<% content_for :description do %>My Description<% end %>

<% if logged_in? %>

    <%= form_with url: '/list_search', method: :get, local: true do |form| %>
        <%= form.label :q, 'Search for list with item:' %>
        <%= form.text_field :q, id: :q %>
        <%= form.submit 'Search' %>
    <% end %>

    <% unless @search_item.nil? || @search_item == [] || @q == "" || @q == " " %>
        <% @search_item.each do |item| %>
        <% item.lists.each do |list| %>
            <p><%= link_to list.name, list_path(list) %></p>
        <% end %>
        <% end %>
        <hr>
    <% end %>
    
    <h3><%= link_to 'Create New List', new_list_path %></h3>

    <% current_user.lists.each do |list| %>
        <p><%= link_to list.name, list_path(list) %></p>
    <% end %>
<% else %>
    <%= render 'layouts/closed_session' %>
<% end %>

app/views/lists/new.html.erb
<% content_for :title do %>Create New List<% end %>
<% content_for :description do %>My Description<% end %>

<% if flash[:errors] %>
    <ul>
    <% flash[:errors].each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

<% if logged_in? %>
    <%= form_with model: @list do |f| %>
        <h2>List name:<%= f.text_field :name %></h2>

        <h2>Items:</h2><%= f.fields_for :items do |item| %>
            <p><%= item.text_field :name, placeholder: 'Item Name' %></p>
        <% end %>
        <%= f.submit %>
    <% end %>
<% end %>

app/views/lists/show.html.erb
<% content_for :title do %><%= @list.name.titlecase %> List<% end %>
<% content_for :description do %>My Description<% end %>

<% if logged_in? %>
    <% if @list.name.downcase.include?('list')%>
        <h2><%= @list.name.titlecase %></h2>
    <% else %>
        <h2><%= @list.name.titlecase + " List" %></h2>
    <% end %>
        <% @list.list_items.each do |list_item| %>
            <p><%= list_item.item.name %></p>
        <% end %>

    <%= form_tag edit_list_path, method: 'get' do %>
        <%= submit_tag "Edit list" %>
    <% end %>

    <%= form_tag list_path, method: 'delete' do %>
        <%= submit_tag "Delete list" %>
    <% end %>
    <br>
  <hr>

  <h3>Share list with:</h3>
    <%= form_tag share_list_path, method: 'post' do %>
        <p><%= select_tag "user_id", options_from_collection_for_select(User.where.not(id: current_user.id), "id", "name") %></p>
        <%= submit_tag "Share" %>
    <% end %>
    <br>

    <%= link_to 'Back to all lists', lists_path %>
<% else %>
    <%= link_to 'Login', login_path %>
<% end %>