config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :recipes
  resources :items
  resources :lists
  resources :users

  resources :sessions, only: [:create]
  get '/sessions', to: 'sessions#new'
  delete '/sessions', to: 'sessions#destroy', as: 'logout'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/recipes/:id', to: 'recipes#add_to_list', as: 'add_to_list'
  post '/lists/:id', to: 'lists#share', as: 'share_list'

  get '/recipe_search', to: 'recipes#search', as: 'recipe_search'
  get '/list_search', to: 'lists#search', as: 'list_search'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :recipe_items
    has_many :items, through: :recipe_items
    belongs_to :user
    accepts_nested_attributes_for :items

    def items_attributes=(item_attributes)
        item_attributes.values.each do |item_attributes|
            if item_attributes[:name] != ""
                item = Item.find_or_create_by(item_attributes)
                item.update(name: item.name.downcase)
                self.items << item
            end
        end
    end

    def quantity
        id = self.id
        RecipeItem.find_by(recipe_id: id).item_quantity
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :add_to_list]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    8.times do
      @recipe.items.new
    end
  end

  def create
    @recipe  = Recipe.new(recipe_params)
    if @recipe.img_url == ""
      @recipe.update(img_url: "default_recipe_img.png")
    end
    if @recipe.update(user_id: current_user.id)
      redirect_to @recipe
    else
      flash[:alert] = @recipe.errors.full_messages
      redirect_to new_recipe_path
    end
  end

  def show
  end

  def edit
    4.times do
      @recipe.items.new
    end
  end

  def update
    RecipeItem.where(recipe_id: params[:id]).destroy_all
    @recipe.update(recipe_params)
    if @recipe.img_url == ""
      @recipe.update(img_url: "default_recipe_img.png")
    end
    redirect_to @recipe
  end

  def destroy
    @recipe.recipe_items.each do |recipe_item|
      recipe_item.destroy
    end
    @recipe.destroy
    redirect_to recipes_path
  end

  def add_to_list
    @recipe.items.each do |item|
      ListItem.find_or_create_by(item_id: item.id, list_id: params[:list])
    end
    @list = List.find(params[:list])
    redirect_to @list
  end

  def search
    # search_item = Item.find_by(name: params[:q])
    @q = params[:q].downcase
    @search_item = Item.where('name LIKE ?', "%#{@q}%")

    if @search_item == [] || @q == "" || @q == " "
      flash[:alert] = "No recipes include #{@q}."
      render :index
    else
      flash.clear
      @search_item
      render :index
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :instructions, :user_id, :img_url, item_ids:[], items_attributes: [:name], recipe_items_attributes: [:item_quantity])
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/edit.html.erb
<% content_for :title do %>Edit <%= @recipe.name.titlecase %> Recipe<% end %>
<% content_for :description do %>My Description<% end %>

<% if flash[:errors] %>
    <% flash[:errors].each do |msg| %>
        <ul>
            <li> <%= msg %></li>
        </ul>
    <% end %>
<% end %>

<%= form_with model: @recipe do |f| %>
    <h2>Recipe name:<%= f.text_field :name %></h2>
    <h4>Recipe by: <%= current_user.name.titlecase %></h4>

    <h2>Items:</h2><%= f.fields_for :items do |item| %>
        <p><%#= @recipe.quantity %> <%= item.text_field :name, placeholder: 'Add new item' %></p>
    <% end %>
    <h2>Image Link:</h2>
            <p><%= f.url_field :img_url, placeholder: 'Image Link' %></p>
    <h2>Instructions:</h2>
    <p><%= f.text_area :instructions %></p>
    <%= f.submit %>
<% end %>

app/views/recipes/index.html.erb
<% content_for :title do %>Recipes<% end %>

<% if logged_in? %>
<%# make sure you config 'routes' get '/search', to: 'indexs#search' in your controller %>
    <%= form_with url: '/recipe_search', method: :get, local: true do |form| %>
        <%= form.label :q, 'Search for recipe with item:' %>
        <%= form.text_field :q, id: :q %>
        <%= form.submit 'Search' %>
    <% end %>

    <% unless @search_item.nil? || @search_item == [] || @q == "" || @q == " " %>
        <% @search_item.each do |item| %>
        <% item.recipes.each do |recipe| %>
            <p><%= link_to recipe.name, recipe_path(recipe) %></p>
        <% end %>
        <% end %>
        <hr>
    <% end %>

    <h3><%= link_to 'Create New Recipe', new_recipe_path %></h3>

    <% current_user.recipes.each do |recipe| %>
        <p><%= link_to recipe.name, recipe_path(recipe) %></p>
    <% end %>
<% else %>
    <%= render 'layouts/closed_session' %>
<% end %>

app/views/recipes/new.html.erb
<% content_for :title do %>Create New Recipe<% end %>
<% content_for :description do %>My Description<% end %>

<% if flash[:errors] %>
    <% flash[:errors].each do |msg| %>
        <ul>
            <li> <%= msg %></li>
        </ul>
    <% end %>
<% end %>

<% if logged_in? %>
    <%= form_with model: @recipe do |f| %>
        <h2>Recipe name:<%= f.text_field :name %></h2>
        <h4>Recipe by: <%= current_user.name.titlecase %></h4>
        
        <h2>Items:</h2><%= f.fields_for :items do |item| %>
            <p><%= item.text_field :name, placeholder: 'Item Name' %></p>
        <% end %>
        <h2>Image Link:</h2>
            <p><%= f.url_field :img_url, placeholder: 'Image Link' %></p>
        <h2>Instructions:</h2>
        <p><%= f.text_area :instructions %></p>
        <%= f.submit %>
    <% end %>
<% end %>

app/views/recipes/show.html.erb
<% content_for :title do %><%= @recipe.name.titlecase %> Recipe<% end %>
<% content_for :description do %>My Description<% end %>

<% if logged_in? %>
    <h2><%= @recipe.name.titlecase %></h2>
        <h4>Recipe by: &nbsp;<%= current_user.name.titlecase %> </h4>  
        <% if @recipe.img_url.nil? %>
            <%= image_tag('default_recipe_img.png') %>
        <% else %>
            <%= image_tag(@recipe.img_url) %>
        <% end %>
        <h3>Ingredients: </h3>
            <% @recipe.recipe_items.each do |recipe_item| %>
                <p><%= recipe_item.item.name %></p>
            <% end %>

  <hr>

    <div id="recipe_instructions"><h3>Instructions: </h3>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= @recipe.instructions %>
        <br>
    </div>

        <%= form_tag edit_recipe_path, method: 'get' do %>
            <%= submit_tag "Edit recipe" %>
        <% end %>
        <%= form_tag recipe_path(@recipe.id), method: 'delete' do %>
            <%= submit_tag "Delete recipe" %>
        <% end %>
        <br>

  <hr>

  <h3>Add Items to list:</h3>
        <%= form_tag(add_to_list_path, method: "post") do %>
            <p><%= select_tag "list", options_from_collection_for_select(current_user.lists, "id", "name") %></p>
            <%= submit_tag("Add") %>
        <% end %>
        <br>

        <%= link_to 'Back to all recipes', recipes_path %>
<% else %>
    <%= link_to 'Login', login_path %>
<% end %>