config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :recipes
  resources :items
  resources :lists
  resources :users

  resources :sessions, only: [:create]
  get '/sessions', to: 'sessions#new'
  delete '/sessions', to: 'sessions#destroy', as: 'logout'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/recipes/:id', to: 'recipes#add_to_list', as: 'add_to_list'
  post '/lists/:id', to: 'lists#share', as: 'share_list'

  get '/recipe_search', to: 'recipes#search', as: 'recipe_search'
  get '/list_search', to: 'lists#search', as: 'list_search'
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_lists
    has_many :lists, through: :user_lists
    has_many :recipes
    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit]
  before_action :recipe_analytics, only: [:show]
  before_action :list_analytics, only: [:show]
  # before_action :redirect_to_login_page_if_not_logged_in, except: [:new, :create]  
  def index
    @users = User.all
  end   

  def show
    if session[:user_id] == params[:id].to_i
      @current_user = current_user
    end
  end

  def new
  end

  def create
    user = User.new(user_params)

    if user.save
      session[:user_id] = user.id
      redirect_to user
    else
      flash[:alert] = 'Passwords do not match!'
      redirect_to new_user_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_user_path
  end



  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation)

  end

  def recipe_analytics
    recipe_items = Array.new(0)
    Recipe.all.each do |recipe|
      recipe_items << recipe.items
    end
    recipe_items.flatten!
    data_hash = recipe_items.inject(Hash.new(0)) { |item,v| item[v] += 1; item }
    data_hash = data_hash.sort_by {|i,v| -v}
    @data_recipe = data_hash.map { |item,count| [item.name, count]}
    @data_recipe = @data_recipe[0..10]
  end

  def list_analytics
    list_items = Array.new(0)
    List.all.each do |list|
      list_items << list.items
    end
    list_items.flatten!
    data_hash = list_items.inject(Hash.new(0)) { |item,v| item[v] += 1; item }
    data_hash = data_hash.sort_by {|i,v| -v}
    @data_list = data_hash.map { |item,count| [item.name, count]}
    @data_list = @data_list[0..10]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_analytics.html.erb
<h3>Analytics: </h3>

<% if @data_list[0] != nil %>
  <h5>Most common item is "<%= @data_list[0][0] %>" appearing <%= @data_list[0][1] %> times from the lists. </h5>
<% end %>
<% if @data_recipe[0] != nil %>
  <h5>Most common item is "<%= @data_recipe[0][0] %>" appearing <%= @data_recipe[0][1] %> times from the recipes.</h5>
<% end %>

<p><button onClick="window.location.reload()">Draw chart</button></p>

<div id="chart1" ></div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<%= javascript_tag do -%>
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {
    var data = JSON.parse('<%= @data_recipe.to_json.html_safe -%>');
    data = [['Item name', 'Count']].concat(data);
    data = google.visualization.arrayToDataTable(data);
    var options = {
        title: 'Top 10 items from our recipes',
        pieHole: 0.4,
        backgroundColor: 'transparent',
        titleTextStyle: {
           fontSize: 20
        }
    };

    var chart = new google.visualization.PieChart(document.getElementById('chart1'));
    chart.draw(data, options);
  }
<% end -%>



<div id="chart2" ></div>

<%= javascript_tag do -%>
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {
    var data = JSON.parse('<%= @data_list.to_json.html_safe -%>');
    data = [['Item name', 'Count']].concat(data);
    data = google.visualization.arrayToDataTable(data);
    var options = {
        title: 'Top 10 items from our lists',
        pieHole: 0.4,
        backgroundColor: 'transparent',
        titleTextStyle: {
           fontSize: 20
        }
    };

    var chart = new google.visualization.PieChart(document.getElementById('chart2'));
    chart.draw(data, options);
  }
<% end -%>

app/views/users/index.html.erb
<% content_for :title do %>GRILList<% end %>
<% content_for :description do %>My Description<% end %>

<%= render 'layouts/closed_session' %>

app/views/users/new.html.erb
<% content_for :title do %>GRILList Signup<% end %>
<% content_for :description do %>My Description<% end %>

<% if logged_in? %>
  <br><br>
  <h2>You are already logged in!</h2>
<% else %>
  <%= form_with model: User.new do |f| %>
    <p>Name: &nbsp;<%= f.text_field :name, placeholder: "Type your full name" %></p>
    <p>Username: &nbsp;<%= f.text_field :username, placeholder: "Choose a cute animal" %></p>
    <p>Password: &nbsp;<%= f.password_field :password, placeholder: "Hint: not 'dolphin'" %></p>
    <p>Confirm: &nbsp;<%= f.password_field :password_confirmation, placeholder: "Confirm your password" %></p>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<% content_for :title do %><%= @user.name.titlecase%><% end %>
<% content_for :description do %>My Description<% end %>

<% if @current_user %>
  <h3><%= @user.name.titlecase%>'s Lists</h3>

  <% @user.lists.each do |list| %>
    <p><%= link_to list.name, list_path(list) %></p>
  <% end %>
  <%= button_to "Create List", new_list_path, method: :get, class: 'button' %>
  <br>
  <hr>

  <h3><%= @user.name.titlecase%>'s Recipes</h3>

  <% @user.recipes.each do |recipe| %>
    <p><%= link_to recipe.name, recipe_path(recipe) %></p>
  <% end %>  
 

  <%= button_to "Create Recipe", new_recipe_path, method: :get, class: 'button' %>
  <br>

  <hr>

  <%= render 'analytics' %>
  
<% else %>
  YO. You aren't allowed to see <%= @user.username %>'s secret, brah!!!
<% end %>