config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :recipes
  resources :items
  resources :lists
  resources :users

  resources :sessions, only: [:create]
  get '/sessions', to: 'sessions#new'
  delete '/sessions', to: 'sessions#destroy', as: 'logout'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/recipes/:id', to: 'recipes#add_to_list', as: 'add_to_list'
  post '/lists/:id', to: 'lists#share', as: 'share_list'

  get '/recipe_search', to: 'recipes#search', as: 'recipe_search'
  get '/list_search', to: 'lists#search', as: 'list_search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :recipe_items
    has_many :recipes, through: :recipe_items
    has_many :list_items
    has_many :lists, through: :list_items

    def quantity
        id = self.id
        RecipeItem.find_by(item_id: id).item_quantity
    end
end

app/models/list.rb
class List < ApplicationRecord
    has_many :list_items
    has_many :items, through: :list_items
    has_many :user_lists
    has_many :users, through: :user_lists
    accepts_nested_attributes_for :items, :list_items

    validates :name, presence: true

    # Here we want to 
    def items_attributes=(item_attributes)
        item_attributes.values.each do |item_attributes|
            if item_attributes[:name] != ""
                item = Item.find_or_create_by(item_attributes)
                item.update(name: item.name.downcase)
                self.items << item
            end
        end
    end

    def list_items_attributes=(list_item_attributes)
        list_item_attributes.values.each do |list_item_attributes|
            list_item = ListItem.find_or_create_by(list_item_attributes)
            self.list_items << list_item
        end
    end
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :list
  belongs_to :item
end

app/models/list_user.rb
class ListUser < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :recipe_items
    has_many :items, through: :recipe_items
    belongs_to :user
    accepts_nested_attributes_for :items

    def items_attributes=(item_attributes)
        item_attributes.values.each do |item_attributes|
            if item_attributes[:name] != ""
                item = Item.find_or_create_by(item_attributes)
                item.update(name: item.name.downcase)
                self.items << item
            end
        end
    end

    def quantity
        id = self.id
        RecipeItem.find_by(recipe_id: id).item_quantity
    end
end

app/models/recipe_item.rb
class RecipeItem < ApplicationRecord
  belongs_to :recipe
  belongs_to :item

  def recipe_item_name
    id = self.item_id
    Item.find(id).name
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_lists
    has_many :lists, through: :user_lists
    has_many :recipes
    has_secure_password
end

app/models/user_list.rb
class UserList < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy, :share]

  def index
    @lists = List.all
  end

  def new
    @list = List.new

    8.times do
      @list.items.new
    end
  end

  def create
    @list  = List.new(list_params)
    if @list.save
      UserList.create(user_id: session[:user_id],list_id: @list.id)
      redirect_to @list
    else
      flash[:errors] = @list.errors.full_messages
      redirect_to new_list_path
    end
  end

  def show
  end

  def edit
    4.times do
      @list.items.new
    end
  end

  def update
    ListItem.where(list_id: @list.id).destroy_all
    @list.update(list_params)
    redirect_to @list
  end

  def destroy
    @list.list_items.each do |list_item|
      list_item.destroy
    end
    @list.user_lists.each do |user_list|
      user_list.destroy
    end
    @list.destroy
    redirect_to lists_path
  end

  def share
    if UserList.find_by(user_id: params[:user_id], list_id: @list.id)
      flash[:alert] = "Already shared list with #{User.find(params[:user_id]).name}!"
    else
      UserList.find_or_create_by(user_id: params[:user_id], list_id: @list.id)
      flash[:notice] = "Shared list with #{User.find(params[:user_id]).name}!"
    end
    redirect_to @list
  end

  def search
    # search_item = Item.find_by(name: params[:q])
    @q = params[:q].downcase
    @search_item = Item.where('name LIKE ?', "%#{@q}%")


    if @search_item == [] || @q == "" || @q == " "
      flash[:alert] = "No lists include #{@q}."
      render :index
    else
      flash.clear
      @search_item
      render :index
    end
  end
  private

  def list_params
    params.require(:list).permit(:name, item_ids:[], items_attributes: [:name])
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit]
  before_action :recipe_analytics, only: [:show]
  before_action :list_analytics, only: [:show]
  # before_action :redirect_to_login_page_if_not_logged_in, except: [:new, :create]  
  def index
    @users = User.all
  end   

  def show
    if session[:user_id] == params[:id].to_i
      @current_user = current_user
    end
  end

  def new
  end

  def create
    user = User.new(user_params)

    if user.save
      session[:user_id] = user.id
      redirect_to user
    else
      flash[:alert] = 'Passwords do not match!'
      redirect_to new_user_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_user_path
  end



  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation)

  end

  def recipe_analytics
    recipe_items = Array.new(0)
    Recipe.all.each do |recipe|
      recipe_items << recipe.items
    end
    recipe_items.flatten!
    data_hash = recipe_items.inject(Hash.new(0)) { |item,v| item[v] += 1; item }
    data_hash = data_hash.sort_by {|i,v| -v}
    @data_recipe = data_hash.map { |item,count| [item.name, count]}
    @data_recipe = @data_recipe[0..10]
  end

  def list_analytics
    list_items = Array.new(0)
    List.all.each do |list|
      list_items << list.items
    end
    list_items.flatten!
    data_hash = list_items.inject(Hash.new(0)) { |item,v| item[v] += 1; item }
    data_hash = data_hash.sort_by {|i,v| -v}
    @data_list = data_hash.map { |item,count| [item.name, count]}
    @data_list = @data_list[0..10]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/recipe_items_helper.rb
module RecipeItemsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_lists_helper.rb
module UserListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_closed_session.html.erb
<%= form_with url: '/sessions' do |f| %>
  <p><%= f.text_field :username, placeholder: "Username" %></p>
  <p><%= f.password_field :password, placeholder: "Password" %></p>
  <p><%= f.submit 'Login' %></p>
<% end %>

<h3>or</h3>

<%= link_to 'Sign Up', signup_path %>

app/views/layouts/_messages.html.erb
<% unless flash.nil? %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <% if logged_in? %>
    <li><%= link_to image_tag('logouttext.png'), logout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to image_tag('logintext.png'), login_path %></li>
  <% end %>
  <li><%= link_to image_tag('listtext.png'), lists_path %></li>
  <li><%= link_to image_tag('recipestext.png'), recipes_path %></li>
  <% if logged_in? %>
    <li><%= link_to image_tag('homegrilltext.png'), user_path(current_user) %></li>
  <% else %>
    <li><%= link_to image_tag('awaygrilltext.png'), root_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GRILList" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "A Rails Application for Grocery Shopper" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Acme" rel="stylesheet">
  </head>
  <body>
    <header>
      <h1>GRILList</h1><%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>